default:
  http_metas:
    content-type: text/html

  metas:
    title:        Douche Crunch
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main]
  javascripts:    [jquery,jquery.input_hint.js,common]
 
  has_layout:     true
  layout:         layout