<?php


/**
 * This class defines the structure of the 'douche' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu Apr  1 15:31:52 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class DoucheTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.DoucheTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('douche');
		$this->setPhpName('Douche');
		$this->setClassname('Douche');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('SUBMIT_IP', 'SubmitIp', 'INTEGER', false, 11, null);
		$this->addColumn('TWITTER_ID', 'TwitterId', 'VARCHAR', false, 255, null);
		$this->addColumn('TWITTER_NAME', 'TwitterName', 'VARCHAR', true, 255, null);
		$this->addColumn('IMAGE_URL', 'ImageUrl', 'VARCHAR', false, 255, null);
		$this->addColumn('FOLLOWER_COUNT', 'FollowerCount', 'INTEGER', false, 11, null);
		$this->addColumn('LATEST_TWEET', 'LatestTweet', 'VARCHAR', false, 255, null);
		$this->addColumn('DISPLAY', 'Display', 'BOOLEAN', true, null, false);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('DoucheVote', 'DoucheVote', RelationMap::ONE_TO_MANY, array('id' => 'douche_id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // DoucheTableMap
