<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/01 17:03:45

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=DoucheCrunch;host=localhost',
  'username' => 'DouchCrunch3000',
  'password' => 'Y3sIAmTh47Aw3s0m3',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
