<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/04/01 17:03:45
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => '/Users/rob/Sites/douche-crunch/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'basedoucheformfilter' => '/Users/rob/Sites/douche-crunch/lib/filter/base/BaseDoucheFormFilter.class.php',
  'basedouchevoteformfilter' => '/Users/rob/Sites/douche-crunch/lib/filter/base/BaseDoucheVoteFormFilter.class.php',
  'baseformfilterpropel' => '/Users/rob/Sites/douche-crunch/lib/filter/BaseFormFilterPropel.class.php',
  'doucheformfilter' => '/Users/rob/Sites/douche-crunch/lib/filter/DoucheFormFilter.class.php',
  'douchevoteformfilter' => '/Users/rob/Sites/douche-crunch/lib/filter/DoucheVoteFormFilter.class.php',
  'basedoucheform' => '/Users/rob/Sites/douche-crunch/lib/form/base/BaseDoucheForm.class.php',
  'basedouchevoteform' => '/Users/rob/Sites/douche-crunch/lib/form/base/BaseDoucheVoteForm.class.php',
  'baseform' => '/Users/rob/Sites/douche-crunch/lib/form/BaseForm.class.php',
  'baseformpropel' => '/Users/rob/Sites/douche-crunch/lib/form/BaseFormPropel.class.php',
  'doucheform' => '/Users/rob/Sites/douche-crunch/lib/form/DoucheForm.class.php',
  'douchevoteform' => '/Users/rob/Sites/douche-crunch/lib/form/DoucheVoteForm.class.php',
  'newdoucheform' => '/Users/rob/Sites/douche-crunch/lib/form/NewDoucheForm.class.php',

  // project_model
  'douche' => '/Users/rob/Sites/douche-crunch/lib/model/Douche.php',
  'douchepeer' => '/Users/rob/Sites/douche-crunch/lib/model/DouchePeer.php',
  'douchevote' => '/Users/rob/Sites/douche-crunch/lib/model/DoucheVote.php',
  'douchevotepeer' => '/Users/rob/Sites/douche-crunch/lib/model/DoucheVotePeer.php',
  'douchetablemap' => '/Users/rob/Sites/douche-crunch/lib/model/map/DoucheTableMap.php',
  'douchevotetablemap' => '/Users/rob/Sites/douche-crunch/lib/model/map/DoucheVoteTableMap.php',
  'basedouche' => '/Users/rob/Sites/douche-crunch/lib/model/om/BaseDouche.php',
  'basedouchepeer' => '/Users/rob/Sites/douche-crunch/lib/model/om/BaseDouchePeer.php',
  'basedouchevote' => '/Users/rob/Sites/douche-crunch/lib/model/om/BaseDoucheVote.php',
  'basedouchevotepeer' => '/Users/rob/Sites/douche-crunch/lib/model/om/BaseDoucheVotePeer.php',

  // application
  'myuser' => '/Users/rob/Sites/douche-crunch/apps/frontend/lib/myUser.class.php',

  // modules
);
