errors:
  url:		/error/:action
  param: { module: errors }

about:
  url:	/about/:action
  param: { module: about }

douche:
  class:   sfPropelRouteCollection
  options: { model: Douche }

douche_confirm:
  url:     /:twitter_screen_name/yeah-they-are
  class:   sfPropelRoute
  options: { model: Douche, type: object }
  param:   { module: douche, action: confirm }
  requirements:
    sf_method: [get]

douche_deny:
  url:     /:twitter_screen_name/not-so-much
  class:   sfPropelRoute
  options: { model: Douche, type: object }
  param:   { module: douche, action: deny }
  requirements:
    sf_method: [get]

douche_view:
  url:     /:twitter_screen_name/:twitter_name_slug
  class:   sfPropelRoute
  options: { model: Douche, type: object }
  param:   { module: douche, action: show }
  requirements:
    sf_method: [get]



homepage:
  url:   /
  param: { module: douche, action: index }