douche:
  class:   sfPropelRouteCollection
  options: { model: Douche }

douche_view:
  url:     /:twitter_screen_name
  class:   sfPropelRoute
  options: { model: Douche, type: object }
  param:   { module: douche, action: show }
  requirements:
    id: \s+
    sf_method: [get]

douche_confirm:
  url:     /:twitter_screen_name/yeah-they-are
  class:   sfPropelRoute
  options: { model: Douche, type: object }
  param:   { module: douche, action: confirm }
  requirements:
    id: \s+
    sf_method: [get]

douche_deny:
  url:     /:twitter_screen_name/not-so-much
  class:   sfPropelRoute
  options: { model: Douche, type: object }
  param:   { module: douche, action: deny }
  requirements:
    id: \s+
    sf_method: [get]

homepage:
  url:   /
  param: { module: douche, action: index }