<?php


/**
 * Skeleton subclass for performing query and update operations on the 'douche' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu Apr  1 14:06:29 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DouchePeer extends BaseDouchePeer {
	public static function retrieveByTwitterScreenName($twitter_screen_name) {
		$c = new Criteria;
		$c->add(DouchePeer::TWITTER_SCREEN_NAME, $twitter_screen_name);
		return DouchePeer::doSelectOne($c);
	}

	public static function getMostDouchey(Criteria $crit = null) {
		if ($crit instanceof Criteria) {
			$c = clone $crit;
		} else {
			$c = new Criteria;
		}

		DouchePeer::addSelectColumns($c);

		if ($c instanceof Criteria) {
			$c->addSelectColumn('SUM(' . DoucheVotePeer::VOTE . ') AS total_doucheyness');
			$c->addDescendingOrderByColumn('total_doucheyness');
			$c->addGroupByColumn(DoucheVotePeer::DOUCHE_ID);
			$c->add(DouchePeer::ID, DouchePeer::ID . ' = ' . DoucheVotePeer::DOUCHE_ID, Criteria::CUSTOM);
			$c->setLimit(10);
		}

		return DouchePeer::doSelect($c);
	}

	/**
	 * Retrieve a single, random user to start from.
	 * 
	 * @param Criteria $crit
	 * @return Douche
	 */
	public static function retrieveRandom(Criteria $crit = null) {
		if ($crit instanceof Criteria) {
			$c = clone $crit;
		} else {
			$c = new Criteria;
		}

		$total = self::doCount($c);
		$rand = rand(0, $total - 1);

		$c->setOffset($rand);

		return DouchePeer::doSelectOne($c);
	}
} // DouchePeer
