<?php


/**
 * Skeleton subclass for performing query and update operations on the 'douche' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu Apr  1 14:06:29 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DouchePeer extends BaseDouchePeer {
	public static function retrieveByTwitterName($twitter_name) {
		$c = new Criteria;
		$c->add(DouchePeer::TWITTER_NAME, $twitter_name);
		return self::doSelectOne($c);
	}
} // DouchePeer
