<?php


/**
 * Skeleton subclass for representing a row from the 'douche' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu Apr  1 14:06:29 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Douche extends BaseDouche {
	protected $twitter_data = array();

	/**
	 * Initializes internal state of Douche object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	public function __toString() {
		return $this->getTwitterName();
	}

	protected function retrieveFromTwitter() {
		if ($this->twitter_data !== array()) {
			return true;
		}
		$twitter = new Twitter(sfConfig::get('app_twitter_username'), sfConfig::get('app_twitter_password'));
		$data = json_decode($twitter->showUser(array('screen_name' => $this->getTwitterName()), 'json'), true);
		if (isset($data['error'])) {
			return false;
		}

		$this->twitter_data = $data;
		return true;
	}

	protected function updateAllFromTwitter() {

	}

	protected function updateTwitterId() {
		$this->updateFromTwitter('id', DouchePeer::TWITTER_ID);
		//$this->updateFromTwitter
	}

	/**
	 * Update a value from the twitter data
	 * @param string Source index from the twitter_data array
	 * @param sring $destination Destination DouchePeer::COL_NAME constant
	 * @return bool
	 */
	protected function updateFromTwitter($source, $destination) {
		if (!$this->retrieveFromTwitter()) {
			return false;
		}

		if (isset($this->twitter_data[$source])) {
			$this->setByName($destination, $this->twitter_data[$source], BasePeer::TYPE_COLNAME);
			return true;
		}

		return false;
	}




} // Douche
