<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/01 17:08:17
sfConfig::add(array(
  'app_twitter_username' => 'douchecrunch',
  'app_twitter_password' => 'jA55PhuXES4ahetrazepReS9qe2WeFUchaduSu4hEmETh',
));
